services:
  db:
    image: mysql:8.0.31
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_RANDOM_ROOT_PASSWORD: "no"
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
